image: node:15.12-alpine3.13

stages:
  - test
  - deploy

test:
  tags:
    - experimental
  stage: test
  script:
  - cd documentation
  - npm install --registry=https://nexus.sberbank.kz/#browse/browse:npm-bank --strict-ssl=false
  - export DOC_INCLUDE_CURRENT_VERSION=false
  - npm run build
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  tags:
    - experimental
  stage: deploy
  script:
  - cd documentation
  - npm install --registry=https://nexus.sberbank.kz/#browse/browse:npm-bank --strict-ssl=false
  - export DOC_INCLUDE_CURRENT_VERSION=false
  - npm run build
  - mv ./build ../public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
